name: minmax-adv-neurips21
channels:
  - defaults
dependencies:
  - python=3.6
  - numpy==1.16.5
  - matplotlib==3.0.3
  - scipy==1.2.1
  - pandas==0.24.2
  - seaborn==0.9.0
  - pip
  - pip:
    - tensorflow-gpu==1.15.0
    - keras==2.2.4
    - tabulate==0.8.3
